name: condominio
description: "Portobello di gallura condominio"
publish_to: 'none'
version: 1.0.1+3

environment:
  sdk: ^3.5.4

dependencies:
  http: ^1.2.0
  flutter_mailer: ^2.0.0
  mailer: ^6.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^18.0.1
  webview_flutter: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/4.jpeg
    - assets/logo.png
    - assets/bombole-gas.png
    - assets/ritiro-rifiuti.png
    - assets/segnalazione-guasto.png
    - assets/ormeggio.png
    - assets/emergenza.png
    - assets/guasto.png
    - assets/ritiro_rifiuti.png
  
  fonts:
    - family: Karla
      fonts:
        - asset: fonts/Karla-Regular.ttf
        - asset: fonts/Karla-Bold.ttf
          weight: 700
